In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [2]:
df=pd.read_csv('student_performance.csv')
df.head()

,Student_ID,Name,Age,Program,Python,Mathematics,Statistics,Machine_Learning,Attendance
0,S001,Ali Khan,20,AI,85,78,92,88,95
1,S002,Sara Ahmed,21,AI,72,75,70,80,90
2,S003,Ahmed Raza,22,SE,90,88,91,93,96
3,S004,Fatima Noor,20,DS,65,70,68,72,85
4,S005,Usman Ali,21,AI,78,82,80,76,88

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Student_ID        20 non-null     object
 1   Name              20 non-null     object
 2   Age               20 non-null     int64
 3   Program           20 non-null     object
 4   Python            20 non-null     int64
 5   Mathematics       20 non-null     int64
 6   Statistics        20 non-null     int64
 7   Machine_Learning  20 non-null     int64
 8   Attendance        20 non-null     int64
dtypes: int64(6), object(3)
memory usage: 1.5+ KB

Check missing values

In [4]:
df.isnull().sum()

Student_ID          0
Name                0
Age                 0
Program             0
Python              0
Mathematics         0
Statistics          0
Machine_Learning    0
Attendance          0
dtype: int64

avg_score column

In [7]:
SUBJECTS=["Python", "Mathematics", "Statistics", "Machine_Learning"]
df["Average_Score"] = df[SUBJECTS].mean(axis=1)
df[["Name"] + SUBJECTS + ["Average_Score"]].head()

,Name,Python,Mathematics,Statistics,Machine_Learning,Average_Score
0,Ali Khan,85,78,92,88,85.75
1,Sara Ahmed,72,75,70,80,74.25
2,Ahmed Raza,90,88,91,93,90.50
3,Fatima Noor,65,70,68,72,68.75
4,Usman Ali,78,82,80,76,79.00

Lebel encoding on categorical column

In [ ]:
le = LabelEncoder()
df["Program"] = ["CS", "SE", "CS", "AI", "DS"]  # or appropriate program values
df["Program_Encoded"] = le.fit_transform(df["Program"])
df[["Program", "Program_Encoded"]].drop_duplicates()

KeyError: 'Program'