In [1]:
import pandas as pd
df=pd.read_csv('student_performance.csv')

In [2]:
df.head()

,Student_ID,Name,Age,Program,Python,Mathematics,Statistics,Machine_Learning,Attendance
0,S001,Ali Khan,20,AI,85,78,92,88,95
1,S002,Sara Ahmed,21,AI,72,75,70,80,90
2,S003,Ahmed Raza,22,SE,90,88,91,93,96
3,S004,Fatima Noor,20,DS,65,70,68,72,85
4,S005,Usman Ali,21,AI,78,82,80,76,88

In [3]:
df.tail()

,Student_ID,Name,Age,Program,Python,Mathematics,Statistics,Machine_Learning,Attendance
15,S016,Hira Shah,21,DS,89,91,88,90,96
16,S017,Omar Farooq,20,AI,74,72,76,78,84
17,S018,Laiba Khan,22,SE,97,95,98,99,100
18,S019,Abdullah,21,DS,68,66,70,72,80
19,S020,Mehwish,20,AI,86,89,87,90,93

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Student_ID        20 non-null     object
 1   Name              20 non-null     object
 2   Age               20 non-null     int64
 3   Program           20 non-null     object
 4   Python            20 non-null     int64
 5   Mathematics       20 non-null     int64
 6   Statistics        20 non-null     int64
 7   Machine_Learning  20 non-null     int64
 8   Attendance        20 non-null     int64
dtypes: int64(6), object(3)
memory usage: 1.5+ KB

In [5]:
df.describe()

,Age,Python,Mathematics,Statistics,Machine_Learning,Attendance
count,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
mean,21.100000,78.900000,79.500000,80.600000,82.600000,89.600000
std,1.020836,11.702002,10.226385,11.366618,10.575045,7.170113
min,20.000000,55.000000,60.000000,58.000000,62.000000,75.000000
25%,20.000000,71.250000,71.750000,73.000000,75.000000,84.750000
50%,21.000000,79.500000,80.000000,79.500000,82.500000,90.500000
75%,22.000000,88.250000,88.250000,90.250000,90.250000,95.250000
max,23.000000,97.000000,95.000000,98.000000,99.000000,100.000000

In [6]:
df.isnull().sum()

Student_ID          0
Name                0
Age                 0
Program             0
Python              0
Mathematics         0
Statistics          0
Machine_Learning    0
Attendance          0
dtype: int64

In [7]:
df['Age']

0     20
1     21
2     22
3     20
4     21
5     22
6     20
7     21
8     23
9     20
10    22
11    21
12    20
13    22
14    23
15    21
16    20
17    22
18    21
19    20
Name: Age, dtype: int64

In [8]:
df[['Name', 'Age']]

              Name  Age
0         Ali Khan   20
1       Sara Ahmed   21
2       Ahmed Raza   22
3      Fatima Noor   20
4        Usman Ali   21
5     Ayesha Malik   22
6     Hassan Tariq   20
7     Zainab Iqbal   21
8      Bilal Ahmed   23
9      Maryam Khan   20
10  Hamza Siddiqui   22
11     Noor Fatima   21
12     Talha Javed   20
13      Iqra Aslam   22
14      Danish Ali   23
15       Hira Shah   21
16     Omar Farooq   20
17      Laiba Khan   22
18        Abdullah   21
19         Mehwish   20

In [9]:
df.loc[0]

Student_ID              S001
Name                Ali Khan
Age                       20
Program                   AI
Python                    85
Mathematics               78
Statistics                92
Machine_Learning          88
Attendance                95
Name: 0, dtype: object

In [10]:
df[df['Age'] > 21]

,Student_ID,Name,Age,Program,Python,Mathematics,Statistics,Machine_Learning,Attendance
2,S003,Ahmed Raza,22,SE,90,88,91,93,96
5,S006,Ayesha Malik,22,SE,95,94,96,97,99
8,S009,Bilal Ahmed,23,SE,73,77,75,79,82
10,S011,Hamza Siddiqui,22,AI,69,71,74,70,87
13,S014,Iqra Aslam,22,AI,84,83,86,88,92
14,S015,Danish Ali,23,SE,61,65,63,67,78
17,S018,Laiba Khan,22,SE,97,95,98,99,100